name: Update aboveS20 Branches

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:          
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Delete branches locally and on remote
        run: |
          git push origin --delete aboveS20 || true
          git branch -D aboveS20 || true

      - name: Create aboveS20 branch from master and modify inc.h
        run: |
          git checkout master
          git checkout -b aboveS20
          echo '#define ABOVE_S20' | cat - "./Project Reboot 3.0/inc.h" > temp && mv temp "./Project Reboot 3.0/inc.h"
          git add "./Project Reboot 3.0/inc.h"
          git commit -m "Add #define ABOVE_S20 to inc.h in aboveS20 branch"
          git push origin aboveS20

  build-master:
    uses: ./.github/workflows/msbuild.yml
    needs: update-branches
    with:
      branch: master

  build-aboveS20:
    uses: ./.github/workflows/msbuild.yml
    needs: update-branches
    with:
      branch: aboveS20
